
export ROCKSDB_FORCE_DIRECT_BUFFER_ZERO_COPY=true
export TOPLINGDB_EAGER_FETCH_VALUE=true

#export CXX=g++-12
#export CC=gcc-12
#export DEBUG_LEVEL=1

export CPU="-march=native"
export UPDATE_REPO=0
export BUILD_PREFIX=../build-toplingdb/
export PREFIX=/opt
export EXTRA_CXXFLAGS='-DROCKSDB_DYNAMIC_CREATE_CF -DTOPLINGDB_WITH_TIMESTAMP -DTOPLINGDB_WITH_WIDE_COLUMNS -DTOPLINGDB_WITH_FABRICATED_COMPLEXITY -DROCKSDB_UNIT_TEST'
#export RUN_JAVA_TESTS='%PerfContextTest'

make -j`nproc` jtest
